# Generated by Django 5.0.4 on 2026-03-19 08:47

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('topic', models.CharField(db_index=True, max_length=100)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generating', 'Generating'), ('published', 'Published'), ('archived', 'Archived'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('question_count', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('time_limit_minutes', models.PositiveSmallIntegerField(blank=True, help_text='0 or null means no time limit', null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('ai_model_used', models.CharField(blank=True, max_length=100)),
                ('ai_prompt_used', models.TextField(blank=True)),
                ('generation_error', models.TextField(blank=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('avg_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quizzes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quizzes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('tf', 'True / False'), ('short', 'Short Answer')], default='mcq', max_length=10)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('text', models.TextField()),
                ('explanation', models.TextField(blank=True, help_text='Shown after answering')),
                ('points', models.PositiveSmallIntegerField(default=1)),
                ('options', models.JSONField(default=list)),
                ('correct_answer', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.quiz')),
            ],
            options={
                'db_table': 'questions',
                'ordering': ['quiz', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('timed_out', 'Timed Out'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_taken_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('total_questions', models.PositiveSmallIntegerField(default=0)),
                ('correct_answers', models.PositiveSmallIntegerField(default=0)),
                ('total_points_earned', models.PositiveSmallIntegerField(default=0)),
                ('total_points_possible', models.PositiveSmallIntegerField(default=0)),
                ('score_percentage', models.FloatField(default=0.0)),
                ('difficulty_at_attempt', models.CharField(blank=True, max_length=10)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quizzes.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quiz_attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selected_answer', models.JSONField()),
                ('is_correct', models.BooleanField(default=False)),
                ('points_earned', models.PositiveSmallIntegerField(default=0)),
                ('time_taken_seconds', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.quizattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='quizzes.question')),
            ],
            options={
                'db_table': 'user_answers',
            },
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['topic', 'difficulty', 'status'], name='quizzes_topic_e5f05b_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['is_public', 'status'], name='quizzes_is_publ_9115f6_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['creator', 'status'], name='quizzes_creator_6b0893_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['quiz', 'order'], name='questions_quiz_id_7f1263_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('quiz', 'order')},
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user', 'status'], name='quiz_attemp_user_id_da1ab5_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['quiz', 'status'], name='quiz_attemp_quiz_id_6a0820_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user', 'quiz'], name='quiz_attemp_user_id_558d63_idx'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['attempt', 'question'], name='user_answer_attempt_b3ca01_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('attempt', 'question')},
        ),
    ]
