# Generated by Django 5.0.4 on 2026-03-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='allow_retake',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='pass_percentage',
            field=models.FloatField(default=60.0),
        ),
    ]
