import uuid
from django.db import models
from django.conf import settings


class QuizAnalyticsSnapshot(models.Model):
    """
    Daily denormalised snapshot of quiz-level statistics.
    Generated by a management command / scheduled task.
    Enables fast trend queries without hitting the attempts table.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    quiz = models.ForeignKey(
        'quizzes.Quiz', on_delete=models.CASCADE, related_name='analytics_snapshots'
    )
    date = models.DateField()
    total_attempts = models.PositiveIntegerField(default=0)
    completed_attempts = models.PositiveIntegerField(default=0)
    average_score = models.FloatField(default=0.0)
    pass_rate = models.FloatField(default=0.0)    # % of completed attempts that passed
    avg_time_seconds = models.FloatField(default=0.0)

    class Meta:
        db_table = 'quiz_analytics_snapshots'
        unique_together = [('quiz', 'date')]
        ordering = ['-date']
        indexes = [models.Index(fields=['quiz', 'date'])]

    def __str__(self):
        return f'{self.quiz.title} — {self.date}'


class UserAnalyticsSummary(models.Model):
    """
    Rolling summary of a user's performance broken down by difficulty and topic.
    Updated incrementally after each attempt completion.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='analytics_summaries'
    )
    period = models.CharField(
        max_length=10,
        choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('all_time', 'All Time')],
    )
    period_start = models.DateField()
    quizzes_taken = models.PositiveIntegerField(default=0)
    questions_answered = models.PositiveIntegerField(default=0)
    correct_answers = models.PositiveIntegerField(default=0)
    average_score = models.FloatField(default=0.0)
    total_time_seconds = models.PositiveIntegerField(default=0)
    # Per-difficulty breakdown stored as JSON
    difficulty_breakdown = models.JSONField(default=dict)
    # Top topics the user has attempted
    topic_breakdown = models.JSONField(default=dict)

    class Meta:
        db_table = 'user_analytics_summaries'
        unique_together = [('user', 'period', 'period_start')]
        ordering = ['-period_start']

    def __str__(self):
        return f'{self.user.username} — {self.period} starting {self.period_start}'

    @property
    def accuracy_percentage(self):
        if not self.questions_answered:
            return 0.0
        return round(self.correct_answers / self.questions_answered * 100, 2)


class QuestionAnalytics(models.Model):
    """
    Per-question aggregated statistics: how often each question is answered
    correctly, how long users take, which option is most chosen, etc.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    question = models.OneToOneField(
        'quizzes.Question', on_delete=models.CASCADE, related_name='analytics'
    )
    total_answers = models.PositiveIntegerField(default=0)
    correct_answers = models.PositiveIntegerField(default=0)
    avg_time_seconds = models.FloatField(default=0.0)
    # {option_id: count}
    option_distribution = models.JSONField(default=dict)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'question_analytics'

    def __str__(self):
        return f'Analytics: {self.question}'

    @property
    def difficulty_rating(self):
        """
        0–1 score where 1 = everyone got it wrong.
        Useful for flagging badly-calibrated questions.
        """
        if not self.total_answers:
            return None
        return round(1 - self.correct_answers / self.total_answers, 2)
