# Generated by Django 5.0.4 on 2026-03-19 08:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizzes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_answers', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('avg_time_seconds', models.FloatField(default=0.0)),
                ('option_distribution', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='quizzes.question')),
            ],
            options={
                'db_table': 'question_analytics',
            },
        ),
        migrations.CreateModel(
            name='QuizAnalyticsSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_attempts', models.PositiveIntegerField(default=0)),
                ('completed_attempts', models.PositiveIntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('pass_rate', models.FloatField(default=0.0)),
                ('avg_time_seconds', models.FloatField(default=0.0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_snapshots', to='quizzes.quiz')),
            ],
            options={
                'db_table': 'quiz_analytics_snapshots',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['quiz', 'date'], name='quiz_analyt_quiz_id_3ae3ab_idx')],
                'unique_together': {('quiz', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UserAnalyticsSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('all_time', 'All Time')], max_length=10)),
                ('period_start', models.DateField()),
                ('quizzes_taken', models.PositiveIntegerField(default=0)),
                ('questions_answered', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('total_time_seconds', models.PositiveIntegerField(default=0)),
                ('difficulty_breakdown', models.JSONField(default=dict)),
                ('topic_breakdown', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_analytics_summaries',
                'ordering': ['-period_start'],
                'unique_together': {('user', 'period', 'period_start')},
            },
        ),
    ]
